version: "2"
linters:
  default: none
  enable:
    - durationcheck
    - errcheck
    - godot
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused

  settings:
    staticcheck:
      checks:
      - "all"
      - "-QF1008"
      - "-ST1003"
    predeclared:
      ignore:
        - new

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - unparam
        path: _test\.go
    paths:
      - cmd
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - cmd
      - third_party$
      - builtin$
      - examples$
