package provider

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	neon "github.com/kislerdm/neon-sdk-go"
)

var _ resource.Resource = (*branchBackupScheduleResource)(nil)
var _ resource.ResourceWithConfigure = (*branchBackupScheduleResource)(nil)

type branchBackupScheduleResource struct {
	client *neon.Client
}

type branchBackupScheduleModel struct {
	ID        types.String              `tfsdk:"id"`
	ProjectID types.String              `tfsdk:"project_id"`
	BranchID  types.String              `tfsdk:"branch_id"`
	Schedule  []backupScheduleItemModel `tfsdk:"schedule"`
}

type backupScheduleItemModel struct {
	Frequency        types.String `tfsdk:"frequency"`
	Day              types.Int64  `tfsdk:"day"`
	Hour             types.Int64  `tfsdk:"hour"`
	Month            types.Int64  `tfsdk:"month"`
	RetentionSeconds types.Int64  `tfsdk:"retention_seconds"`
}

func NewBranchBackupScheduleResource() resource.Resource {
	return &branchBackupScheduleResource{}
}

func (r *branchBackupScheduleResource) Metadata(_ context.Context, _ resource.MetadataRequest,
	resp *resource.MetadataResponse) {
	resp.TypeName = "neon_branch_backup_schedule"
}

func (r *branchBackupScheduleResource) Schema(_ context.Context, _ resource.SchemaRequest,
	resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the automatic snapshot backup schedule for a Neon branch.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "The ID of the backup schedule.",
				Computed:    true,
			},
			"project_id": schema.StringAttribute{
				Description: "The Neon project ID.",
				Required:    true,
			},
			"branch_id": schema.StringAttribute{
				Description: "The Neon branch ID.",
				Required:    true,
			},
			"schedule": schema.ListNestedAttribute{
				Description: "Snapshot frequencies configured for the branch.",
				Required:    true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"frequency": schema.StringAttribute{
							Description: "Snapshot frequency: daily, weekly, or monthly.",
							Required:    true,
							Validators: []validator.String{
								backupFrequencyValidator{},
							},
						},
						"day": schema.Int64Attribute{
							Description: "Day of the week or month, when applicable.",
							Optional:    true,
						},
						"hour": schema.Int64Attribute{
							Description: "Hour of the day, when applicable.",
							Optional:    true,
						},
						"month": schema.Int64Attribute{
							Description: "Month of the year, when applicable.",
							Optional:    true,
						},
						"retention_seconds": schema.Int64Attribute{
							Description: "How long to retain scheduled snapshots, in seconds.",
							Optional:    true,
						},
					},
				},
			},
		},
	}
}

type backupFrequencyValidator struct{}

func (backupFrequencyValidator) Description(context.Context) string {
	return "validates that the backup frequency is supported by the Neon API"
}

func (backupFrequencyValidator) MarkdownDescription(ctx context.Context) string {
	return backupFrequencyValidator{}.Description(ctx)
}

func (backupFrequencyValidator) ValidateString(_ context.Context, req validator.StringRequest,
	resp *validator.StringResponse) {
	if req.ConfigValue.IsNull() || req.ConfigValue.IsUnknown() {
		return
	}

	switch req.ConfigValue.ValueString() {
	case "daily", "weekly", "monthly":
		return
	default:
		resp.Diagnostics.AddAttributeError(
			req.Path,
			"Invalid backup frequency",
			"Supported backup frequencies are daily, weekly, and monthly.",
		)
	}
}

func (r *branchBackupScheduleResource) Configure(_ context.Context, req resource.ConfigureRequest,
	resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*neon.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			"Expected *neon.Client, got an unexpected type.",
		)
		return
	}

	r.client = client
}

func (r *branchBackupScheduleResource) ImportState(ctx context.Context, req resource.ImportStateRequest,
	res *resource.ImportStateResponse) {
	// Import IDs use the same stable composite ID generated by Create:
	// <project_id>/<branch_id>.
	projectID, branchID, ok := strings.Cut(req.ID, "/")
	if !ok || projectID == "" || branchID == "" || strings.Contains(branchID, "/") {
		res.Diagnostics.AddError(
			"Invalid Branch Backup Schedule Import ID",
			"Expected an import ID in the form <project_id>/<branch_id>.",
		)
		return
	}

	state := branchBackupScheduleModel{
		ID:        types.StringValue(req.ID),
		ProjectID: types.StringValue(projectID),
		BranchID:  types.StringValue(branchID),
	}
	res.Diagnostics.Append(res.State.Set(ctx, &state)...)
	r.Read(ctx, resource.ReadRequest{State: res.State}, &resource.ReadResponse{State: res.State})
}

func (r *branchBackupScheduleResource) Create(ctx context.Context, req resource.CreateRequest,
	resp *resource.CreateResponse) {
	if r.client == nil {
		resp.Diagnostics.AddError("Client Not Configured", "The Neon provider client is not configured.")
		return
	}

	var v branchBackupScheduleModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &v)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if _, err := r.client.SetSnapshotSchedule(
		v.ProjectID.ValueString(),
		v.BranchID.ValueString(),
		newBackupSchedule(v.Schedule),
	); err != nil {
		resp.Diagnostics.AddError("Unable to Set Branch Backup Schedule", err.Error())
	} else {
		v.ID = types.StringValue(newBackupScheduleID(v.ProjectID.ValueString(), v.BranchID.ValueString()))
		resp.Diagnostics.Append(resp.State.Set(ctx, &v)...)
	}
}

func (r *branchBackupScheduleResource) Read(ctx context.Context, req resource.ReadRequest,
	resp *resource.ReadResponse) {
	if r.client == nil {
		resp.Diagnostics.AddError("Client Not Configured", "The Neon provider client is not configured.")
		return
	}

	var v branchBackupScheduleModel
	resp.Diagnostics.Append(req.State.Get(ctx, &v)...)
	if resp.Diagnostics.HasError() {
		return
	}

	schedule, err := r.client.GetSnapshotSchedule(v.ProjectID.ValueString(), v.BranchID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Unable to Read Neon Branch Backup Schedule", err.Error())
		return
	}

	v.Schedule = newBackupScheduleItemsModel(schedule.Schedule)
	resp.Diagnostics.Append(resp.State.Set(ctx, &v)...)
}

func (r *branchBackupScheduleResource) Update(ctx context.Context, req resource.UpdateRequest,
	resp *resource.UpdateResponse) {
	if r.client == nil {
		resp.Diagnostics.AddError("Client Not Configured", "The Neon provider client is not configured.")
		return
	}

	var v branchBackupScheduleModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &v)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if _, err := r.client.SetSnapshotSchedule(
		v.ProjectID.ValueString(),
		v.BranchID.ValueString(),
		newBackupSchedule(v.Schedule),
	); err != nil {
		resp.Diagnostics.AddError("Unable to Set Branch Backup Schedule", err.Error())
	} else {
		v.ID = types.StringValue(newBackupScheduleID(v.ProjectID.ValueString(), v.BranchID.ValueString()))
		resp.Diagnostics.Append(resp.State.Set(ctx, &v)...)
	}
}

func (r *branchBackupScheduleResource) Delete(ctx context.Context, req resource.DeleteRequest,
	resp *resource.DeleteResponse) {
	if r.client == nil {
		resp.Diagnostics.AddError("Client Not Configured", "The Neon provider client is not configured.")
		return
	}

	var state branchBackupScheduleModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if _, err := r.client.SetSnapshotSchedule(
		state.ProjectID.ValueString(),
		state.BranchID.ValueString(),
		neon.BackupSchedule{Schedule: []neon.BackupScheduleItem{}},
	); err != nil {
		resp.Diagnostics.AddError("Unable to Delete Branch Backup Schedule", err.Error())
		return
	}

	resp.State.RemoveResource(ctx)
}

func newBackupScheduleID(projectID, branchID string) string {
	return fmt.Sprintf("%s/%s", projectID, branchID)
}

func newBackupSchedule(items []backupScheduleItemModel) neon.BackupSchedule {
	result := neon.BackupSchedule{Schedule: make([]neon.BackupScheduleItem, 0, len(items))}
	for _, item := range items {
		entry := neon.BackupScheduleItem{Frequency: item.Frequency.ValueString()}
		if !item.Day.IsNull() && !item.Day.IsUnknown() {
			day := uint8(item.Day.ValueInt64())
			entry.Day = &day
		}
		if !item.Hour.IsNull() && !item.Hour.IsUnknown() {
			hour := uint8(item.Hour.ValueInt64())
			entry.Hour = &hour
		}
		if !item.Month.IsNull() && !item.Month.IsUnknown() {
			month := uint8(item.Month.ValueInt64())
			entry.Month = &month
		}
		if !item.RetentionSeconds.IsNull() && !item.RetentionSeconds.IsUnknown() {
			retention := uint32(item.RetentionSeconds.ValueInt64())
			entry.RetentionSeconds = &retention
		}
		result.Schedule = append(result.Schedule, entry)
	}
	return result
}

func newBackupScheduleItemsModel(items []neon.BackupScheduleItem) []backupScheduleItemModel {
	result := make([]backupScheduleItemModel, 0, len(items))
	for _, item := range items {
		model := backupScheduleItemModel{Frequency: types.StringValue(item.Frequency)}
		if item.Day != nil {
			model.Day = types.Int64Value(int64(*item.Day))
		}
		if item.Hour != nil {
			model.Hour = types.Int64Value(int64(*item.Hour))
		}
		if item.Month != nil {
			model.Month = types.Int64Value(int64(*item.Month))
		}
		if item.RetentionSeconds != nil {
			model.RetentionSeconds = types.Int64Value(int64(*item.RetentionSeconds))
		}
		result = append(result, model)
	}
	return result
}
